Repository UPbrella/UPbrella_back, pull requests merged in 2023-08, with the labels that each got.

#96 [Refactor] 요구사항 변경에 따른 협업지점 CRUD 리팩토링
  bin/main/application.yml
  bin/main/static/index.html
  bin/test/org/springframework/restdocs/templates/custom-response-fields.snippet
  bin/test/org/springframework/restdocs/templates/request-fields.snippet
  bin/test/org/springframework/restdocs/templates/response-fields.snippet
  build.gradle
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/AllBusinessHourRequest.java
  src/main/java/upbrella/be/store/dto/request/ClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CoordinateRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateStoreRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateSubClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/ImagesRequest.java
  src/main/java/upbrella/be/store/dto/request/SingleBusinessHourRequest.java
  src/main/java/upbrella/be/store/dto/request/UpdateStoreRequest.java
  src/main/java/upbrella/be/store/dto/response/AllBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/AllSubClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/entity/BusinessHour.java
  src/main/java/upbrella/be/store/entity/Classification.java
  src/main/java/upbrella/be/store/entity/ClassificationType.java
  src/main/java/upbrella/be/store/entity/DayOfWeek.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreImage.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/BusinessHourRepository.java
  src/main/java/upbrella/be/store/repository/ClassificationRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/BusinessHourService.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/docs/utils/RestDocsSupport.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: refactor

#98 [feat] OAuth 카카오 로그인 수정, 회원 가입 기능 구현 및 테스트 코드 리팩터링
  src/main/java/upbrella/be/config/WebConfig.java
  src/main/java/upbrella/be/config/interceptor/OAuthLoginInterceptor.java
  src/main/java/upbrella/be/error/controller/ErrorController.java
  src/main/java/upbrella/be/login/controller/LoginController.java
  src/main/java/upbrella/be/login/dto/request/NaverLoginCodeRequest.java
  src/main/java/upbrella/be/login/dto/response/KakoLoginResponse.java
  src/main/java/upbrella/be/login/dto/response/LoggedInUserResponse.java
  src/main/java/upbrella/be/login/dto/response/NaverLoginResponse.java
  src/main/java/upbrella/be/login/dto/response/Properties.java
  src/main/java/upbrella/be/login/dto/token/CommonOauthInfo.java
  src/main/java/upbrella/be/login/dto/token/NaverOauthInfo.java
  src/main/java/upbrella/be/payment/entity/Payment.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/user/config/LoginConfig.java
  src/main/java/upbrella/be/user/controller/LoginExceptionHandler.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/response/KakaoLoginResponse.java
  src/main/java/upbrella/be/user/dto/token/KakaoOauthInfo.java
  src/main/java/upbrella/be/user/dto/token/OauthToken.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/exception/ExistingMemberException.java
  src/main/java/upbrella/be/user/repository/UserRepository.java
  src/main/java/upbrella/be/user/service/OauthLoginService.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/login/controller/LoginControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/OauthLoginServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#108 [Fix] 버그 수정
  .gitignore
  bin/main/application.yml
  bin/main/static/index.html
  bin/test/org/springframework/restdocs/templates/custom-response-fields.snippet
  bin/test/org/springframework/restdocs/templates/request-fields.snippet
  bin/test/org/springframework/restdocs/templates/response-fields.snippet
Labels: fix

#107 [feat] 회원 대여 내역 조회 (#104)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/AllHistoryResponse.java
  src/main/java/upbrella/be/user/dto/response/SingleHistoryResponse.java
  src/test/java/upbrella/be/rent/entity/HistoryTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#105 [feat] 회원 목록 조회 기능 구현 및 테스트 코드 작성 (#103)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/config/WebConfig.java
  src/main/java/upbrella/be/config/interceptor/OAuthLoginInterceptor.java
  src/main/java/upbrella/be/error/controller/ErrorController.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/AllUsersInfoResponse.java
  src/main/java/upbrella/be/user/dto/response/SingleHistoryResponse.java
  src/main/java/upbrella/be/user/dto/response/SingleUserInfoResponse.java
  src/main/java/upbrella/be/user/repository/UserRepository.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#112 [feat] 프로필에 따라 인가 on/off 기능 추가, Jacoco 테스트 시 Jquery 엔티티, lombok 제외 (#110, #111)
  build.gradle
  lombok.config
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/config/WebConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: feat, chore

#113 [chore] 배포 브랜치 충돌 해결
  src/main/java/upbrella/be/error/controller/ErrorController.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: chore

#109 [feat] 현 지도 협업 지점 조회 시 영업 상태 표시 기능 구현 (#106)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/SingleBusinessHourRequest.java
  src/main/java/upbrella/be/store/dto/response/AllCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/entity/BusinessHour.java
  src/main/java/upbrella/be/store/entity/DayOfWeek.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: feat

#115 [feat] 우산 대여/반납 현황 조회 기능 구현 (#47)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/HistoryFilterRequest.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoriesPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: feat

#117 [feat] 개선 요청 목록 조회 기능 구현 및 request parameter 추가에 따른 컨트롤러 테스트 수정 (#49)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/response/ConditionReportPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/ConditionReportResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementReportPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementReportResponse.java
  src/main/java/upbrella/be/rent/entity/ConditionReport.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/repository/ImprovementReportRepository.java
  src/main/java/upbrella/be/rent/service/ConditionReportService.java
  src/main/java/upbrella/be/rent/service/ImprovementReportService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/ConditionReportServiceTest.java
Labels: feat

#118 [refactor] 예외처리 커스텀 예외 생성하여 리팩토링 및 컨트롤러 예외처리, 인터셉터 테스트 추가 (#116)
  .gitignore
  daemon/8.1.1/registry.bin
  daemon/8.1.1/registry.bin.lock
  src/main/java/upbrella/be/error/controller/ErrorController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/exception/DeletedStoreDetailException.java
  src/main/java/upbrella/be/store/exception/NonExistingStoreDetailException.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaExceptionHandler.java
  src/main/java/upbrella/be/umbrella/exception/ExistingUmbrellaUuidException.java
  src/main/java/upbrella/be/umbrella/exception/NonExistingUmbrellaException.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/controller/LoginExceptionHandler.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/controller/UserExceptionHandler.java
  src/main/java/upbrella/be/user/exception/InvalidLoginCodeException.java
  src/main/java/upbrella/be/user/exception/LoginedMemberException.java
  src/main/java/upbrella/be/user/exception/NonExistingMemberException.java
  src/main/java/upbrella/be/user/exception/NotSocialLoginedException.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/util/CustomErrorResponse.java
  src/test/java/upbrella/be/config/interceptor/OAuthLoginInterceptorTest.java
  src/test/java/upbrella/be/docs/utils/RestDocsSupport.java
  src/test/java/upbrella/be/error/controller/ErrorControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: refactor

#125 [feat] 대여 폼으로 이동 시 자동 완성에 필요한 데이터 fetch 기능 구현 및 테스트 작성 (#124)
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/response/RentFormResponse.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: feat

#126 [refactor] store crud 테스트 코드 수정 및 추가 (#121)
  src/main/java/upbrella/be/store/service/BusinessHourService.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/entity/StoreMetaTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: refactor

#128 [refactor] Fixture Monkey 의존성 추가, Umbrella Service 테스트에 적용
  README.md
  build.gradle
  lombok.config
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/store/exception/NonExistingStoreMetaException.java
  src/main/java/upbrella/be/user/dto/token/OauthToken.java
  src/main/java/upbrella/be/user/entity/User.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/config/interceptor/OAuthLoginInterceptorTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/OauthLoginServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: refactor

#123 [docs] 리드미 최신화 (#119)
  README.md
Labels: docs

#131 [feat] 대여한 우산 반납 기능 구현 (#45)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/entity/ConditionReport.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/entity/ImprovementReport.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/ImprovementReportService.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: feat

#132 [feat] 사용자 은행 정보 수정 (#129)
  .gitignore
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/UpdateBankAccountRequest.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/repository/UserRepository.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#135 [refactor] 은행정보 수정 잘못된 코드 수정 (#129)
  src/main/java/upbrella/be/user/dto/request/UpdateBankAccountRequest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: refactor

#138 [feat] 회원 탈퇴 기능 api 추가 (#130)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/entity/BlackList.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/exception/BlackListUserException.java
  src/main/java/upbrella/be/user/exception/ExistingMemberException.java
  src/main/java/upbrella/be/user/exception/NonExistingMemberException.java
  src/main/java/upbrella/be/user/exception/UserException.java
  src/main/java/upbrella/be/user/repository/BlackListRepository.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#143 [feat] 우산 관리 어드민 생성 시각, 특이사항 필드 추가 및 API, test 수정 (#140)
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaCreateRequest.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaModifyRequest.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#145 [refactor] 협업지점 crud 커스텀 에러 적용 (#122)
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/exception/IncorrectClassificationException.java
  src/main/java/upbrella/be/store/exception/NonExistingClassificationException.java
  src/main/java/upbrella/be/store/exception/NonExistingStoreImageException.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: refactor

#149 [refactor] Classification을 삭제할 때 할당되어 있는 경우 400 에러 발생 (#147)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/exception/AssignedClassificationException.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
Labels: refactor

#150 [feat] UmbrellaRepositoryImpl 단위 테스트 작성
  build.gradle
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaExceptionHandler.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/QueryDslTestConfig.java
  src/test/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImplTest.java
Labels: feat

#152 [feat] 협업지점 소개 페이지 조회 api 추가 (#151)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/AllStoreIntroductionResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreIntroductionResponse.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
Labels: feat

#155 [release] make docker file
  .github/workflows/Dockerfile
  .gitignore
  Dockerfile
  src/docs/asciidoc/api/store/store.adoc
Labels: refactor

#154 [refactor] Store Repository 단위 테스트 작성 (#153)
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/store/repository/StoreDetailRepositoryImplTest.java
  src/test/java/upbrella/be/store/repository/StoreMetaRepositoryImplTest.java
Labels: refactor

#158 [feat] 환급 확인, 지불 확인 기능 구현 및 테스트 작성
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/exception/NonExistingHistoryException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/entity/HistoryTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: feat

#159 [feat] redis session server 설정
  build.gradle
  src/main/java/upbrella/be/config/HttpSessionConfig.java
  src/main/resources/application-dev.yml
Labels: feat

#161 [fix] store 관련 api 버그 수정
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: fix

#162 [feat] 도커파일, 도커 이미지 ECR 업로드, ECS 배포 요청 CI/CD 스크립트 작성
  .github/workflows/Dockerfile
  .github/workflows/dev-pr-test.yml
  .github/workflows/dev-release-ci.yml
  .github/workflows/production-pr-test.yml
  .github/workflows/production-release-ci.yml
Labels: feat

#164 [docs] 인프라, CI/CD 흐름도 변경에 따른 Readme.md 업데이트 (#163)
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs

#168 [release]8월 22일 개발 서버 배포
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/Dockerfile
  .github/workflows/dev-pr-test.yml
  .github/workflows/dev-release-ci.yml
  .github/workflows/production-pr-test.yml
  .github/workflows/production-release-ci.yml
  .github/workflows/release-dev-ci.yml
  .github/workflows/release-production-ci.yml
  README.md
  build.gradle
  deploy.sh
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/config/HttpSessionConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/exception/NonExistingHistoryException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/resources/application-dev.yml
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/entity/HistoryTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/repository/StoreDetailRepositoryImplTest.java
  src/test/java/upbrella/be/store/repository/StoreMetaRepositoryImplTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: release

#169 [chore] release production CI script properties 수정
  .github/workflows/release-production-ci.yml
Labels: chore

#175 [release] 개발 서버 0.0.1v-Dev pre-release
  .github/workflows/release-production-ci.yml
Labels: release

#179 [refactor] session user 처리
  src/main/java/upbrella/be/config/interceptor/AdminInterceptor.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/user/dto/response/SessionUser.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: refactor

#181 [release] 개발 서버 0.0.2v-Dev pre-release
  src/main/java/upbrella/be/config/interceptor/AdminInterceptor.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/user/dto/response/SessionUser.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: release

#185 [feat] 우산 반납 시 슬랙 봇 알람 기능 (#184)
  build.gradle
  src/main/java/upbrella/be/config/SlackBotConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/slack/service/SlackAlarmService.java
  src/main/java/upbrella/be/user/dto/response/SessionUser.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/slack/service/SlackAlarmServiceTest.java
Labels: feat

#182 [fix] 지도 상에서 협업지점 목록 조회 로직 수정(#170)
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/CoordinateRequest.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/repository/StoreMetaRepositoryImplTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: fix

#186 [release] 반납 시 슬랙 봇 알람 기능, 로그인 오류 Hot-fix (#184) (#185)
  build.gradle
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/config/SlackBotConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/slack/service/SlackAlarmService.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/CoordinateRequest.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/user/dto/response/SessionUser.java
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/slack/service/SlackAlarmServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/repository/StoreMetaRepositoryImplTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: release

#190 [fix] cors 설정 변경
  src/main/java/upbrella/be/config/WebConfig.java
Labels: fix

#191 fix: cors 설정 변경 (#190)
  src/main/java/upbrella/be/config/WebConfig.java
Labels: release

#192 fix: cors 설정 변경
  src/main/java/upbrella/be/config/WebConfig.java
Labels: fix

#194 [fix] cors 설정 변경
  src/main/java/upbrella/be/config/WebConfig.java
Labels: fix

#195 cors credential 추가
  src/main/java/upbrella/be/config/WebConfig.java
Labels: release
