Repository UPbrella/UPbrella_back, pull requests merged in 2023-09, with the labels that each got.

#189 [feat] 와이어프레임 변경에 따른 대여 내역 조회 응답 dto 수정 (#146)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/response/RentFormResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoriesPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/exception/ExistingUmbrellaForRentException.java
  src/main/java/upbrella/be/rent/exception/NonExistingUmbrellaForRentException.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: feat

#197 [feat] 개인정보 암호화 복호화 기능 추가
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/main/resources/static/index.html
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#199 [fix] 사용자 대여 우산 조회, 대여 내역 조회, 은행 정보 수정 500 에러 수정, CORS OPTIONS 추가(#198, #200)
  src/main/java/upbrella/be/config/WebConfig.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaExceptionHandler.java
  src/main/java/upbrella/be/umbrella/exception/NonExistingBorrowedHistoryException.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: fix

#201 [release] 개발 서버 0.0.4v-Dev pre-release
  src/main/java/upbrella/be/config/WebConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/response/RentFormResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoriesPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/exception/ExistingUmbrellaForRentException.java
  src/main/java/upbrella/be/rent/exception/NonExistingUmbrellaForRentException.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaExceptionHandler.java
  src/main/java/upbrella/be/umbrella/exception/NonExistingBorrowedHistoryException.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/main/resources/static/index.html
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#202 [fix] 협업 지점 상세 이미지 추가 (#196)
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/entity/StoreDetailTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
Labels: fix

#203 [refactor] 대분류 ID로 협업지점 목록 조회 우산 N+1 로직 개선 (#187)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreMetaWithUmbrellaCount.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/repository/StoreMetaRepositoryImplTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: refactor

#204 [fix] CORS 에러 수정
  src/main/java/upbrella/be/config/DevCorsConfig.java
  src/main/java/upbrella/be/config/ProductionCorsConfig.java
Labels: fix

#206 [fix] 반납 여부에 따라 환급 여부가 결정되던 로직을 정상적으로 수정 (#205)
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/service/RentService.java
Labels: fix

#208 [fix] 세션 유저 변경 및 암호화 관련 버그 수정
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
Labels: fix

#214 [feat] 사용자 계좌 삭제 구현 (#213)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#217 [feat] 보증금 환급된 대여 기록의 계좌 정보를 삭제할 수 있다.(#216)
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/exception/NotRefundedException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: feat

#218 [feat] 블랙리스트 관련 API 추가 (#215)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/AllBlackListResponse.java
  src/main/java/upbrella/be/user/dto/response/SingleBlackListResponse.java
  src/main/java/upbrella/be/user/entity/BlackList.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#219 [feat] 어드민 인가 인터셉터 구현 및 Admin api /admin으로 분리 (#210)
  src/docs/asciidoc/api/admin/rent.adoc
  src/docs/asciidoc/api/admin/store.adoc
  src/docs/asciidoc/api/admin/umbrella.adoc
  src/docs/asciidoc/api/admin/user.adoc
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/api/store/store.adoc
  src/docs/asciidoc/api/user/user.adoc
  src/docs/asciidoc/common.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/config/DevCorsConfig.java
  src/main/java/upbrella/be/config/interceptor/AdminInterceptor.java
  src/main/java/upbrella/be/config/interceptor/LoginInterceptor.java
  src/main/java/upbrella/be/config/interceptor/OAuthLoginInterceptor.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/SingleBlackListResponse.java
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/config/interceptor/AdminInterceptorTest.java
  src/test/java/upbrella/be/config/interceptor/LoginInterceptorTest.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#222 [feat] 사용자 로그아웃 기능 (#221)
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/LoginCodeRequest.java
  src/main/resources/application.yml
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#224 [refactor] 블랙리스트에 socialId 추가할 때 해싱 추가 (#223)
  src/main/java/upbrella/be/user/entity/BlackList.java
  src/main/java/upbrella/be/user/service/UserService.java
Labels: refactor

#225 [release] 추가 기능 구현
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/LoginCodeRequest.java
  src/main/java/upbrella/be/user/entity/BlackList.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: release

#229 [feat] User API 기능 추가 (이메일, 관리자 변경) #228
  src/docs/asciidoc/api/admin/user.adoc
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/response/SingleUserInfoResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#237 [feat] 반납 폼 데이터 조회 API 작성 (#212)
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/response/ReturnFormResponse.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#236 [fix] 세션 만료 시 400 -> 401 Unauthorized 수정
  src/main/java/upbrella/be/config/HttpSessionConfig.java
  src/main/java/upbrella/be/error/controller/ErrorController.java
Labels: fix

#238 [feat] 카카오 로그인 시 이메일 수집 (#235)
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/request/KakaoAccount.java
  src/main/java/upbrella/be/user/dto/response/KakaoLoginResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/OauthLoginServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#239 [release] 0.1.1v-Dev pre-release
  src/docs/asciidoc/api/admin/user.adoc
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/config/HttpSessionConfig.java
  src/main/java/upbrella/be/error/controller/ErrorController.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/response/ReturnFormResponse.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/dto/response/AllStoreIntroductionResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreIntroductionResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreIntroductionsResponseByClassification.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/KakaoAccount.java
  src/main/java/upbrella/be/user/dto/response/KakaoLoginResponse.java
  src/main/java/upbrella/be/user/dto/response/SingleUserInfoResponse.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/OauthLoginServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#242 [fix] 로그인 에러 수정 (#241)
  src/main/java/upbrella/be/user/dto/request/KakaoAccount.java
Labels: fix

#243 v0.1.2-dev pre-release
  src/main/java/upbrella/be/user/dto/request/KakaoAccount.java
Labels: release

#244 [feat] 협업지점 활성화/비활성화 api 분리 (#240)
  src/docs/asciidoc/api/admin/store.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/request/UpdateStoreRequest.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/exception/EssentialImageException.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: feat

#245 [fix] 환급되지 않았을 경우 계좌정보 삭제할 수 없도록 예외처리 추가
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
Labels: fix

#247 0.2.0-Dev pre-release
  src/docs/asciidoc/api/admin/store.adoc
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/request/UpdateStoreRequest.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/exception/EssentialImageException.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: release

#250 [refactor] request 값 검증 (#248)
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/AllBusinessHourRequest.java
  src/main/java/upbrella/be/store/dto/request/ClassificationRequest.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaCreateRequest.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaModifyRequest.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: refactor

#251 [refactor]: 암호화 테스트 완료 후 키 설정(#249)
  src/main/java/upbrella/be/util/AesEncryptor.java
Labels: refactor

#256 [fix] 분류명 깨지는 현상 수정 (#254)
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
Labels: fix

#261 [fix] 암호와 에러 수정 (#260)
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: fix

#262 0.3.0 dev pre-release
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/AllBusinessHourRequest.java
  src/main/java/upbrella/be/store/dto/request/ClassificationRequest.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaCreateRequest.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaModifyRequest.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#264 [fix] 정상적으로 로그인하지 않은 경우 예외처리 추가 (#263)
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/controller/UserExceptionHandler.java
  src/main/java/upbrella/be/user/exception/NotLoginException.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: fix

#266 v0.3.1 dev pre-release
  .github/ISSUE_TEMPLATE/fe-요청사항---버그제보-템플릿-.md
  .github/ISSUE_TEMPLATE/feature_request.md
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/controller/UserExceptionHandler.java
  src/main/java/upbrella/be/user/exception/NotLoginException.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#269 [test] 암호화 관련 테스트 추가 (로그인 에러 해결)
  src/test/java/upbrella/be/util/AESTest.java
Labels: test

#268 [fix] Validation 추가 후 테스트 실패 에러 해결(#267)
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
Labels: fix

#270 v0.3.2 dev pre-release
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/util/AESTest.java
Labels: release

#271 [fix] storeDetail 조회 에러 수정 (#265)
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
Labels: fix

#273 v0.3.3 dev pre-release
  src/docs/asciidoc/api/user/user.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
Labels: release

#276 [fix] 유저 대여 내역 조회, 어드민 대여 내역 조회 시 정렬 로직을 ID 역순 정렬로 변경(#253)
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
Labels: fix

#279 [test] 우산 통합 테스트 작성(#183)
  src/test/java/upbrella/be/umbrella/integration/UmbrellaIntegrationTest.java
Labels: test

#285 [refactor] 우산 조회시 ect 추가 (#280)
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
Labels: refactor

#286 [fix] 상태 신고 기록 조회 (#284)
  src/main/java/upbrella/be/rent/service/ConditionReportService.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/umbrella/integration/UmbrellaIntegrationTest.java
Labels: fix

#289 [fix] 우산 Admin 현재 대여 번호, 협업 지점 이름, 협업 지점 ID 통일 (#282)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreIntroductionResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaWithHistory.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryCustom.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/config/interceptor/AuthTestConfig.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/integration/UmbrellaIntegrationTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: fix

#295 [feat]: 로그인 유저 정보 조회시 이메일 정보 추가 (#293)
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#296 [refactor] 암호화 방싱 ECB에서 CBC로 변경 (#275)
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/util/AESTest.java
Labels: refactor

#297 [fix] 하나의 우산 중복 대여 예외처리 (#288)
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/exception/NotAvailableUmbrellaException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: fix

#298 [fix] 대분류 태그별 협업 지점 목록 조회 에러 해결 (#290)
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
Labels: fix

#301 [refactor] 대여 기록 조회 api 성능 개선 (#300)
  src/main/java/upbrella/be/rent/dto/response/HistoryInfoDto.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: refactor

#305 [feat] nGrinder 테스트 자동화 (#304)
  .github/workflows/release-dev-ci.yml
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/util/NGrinderController.java
Labels: feat

#308 v0.3.5 dev pre-release
  .github/workflows/release-dev-ci.yml
  src/main/java/upbrella/be/config/AuthConfig.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/response/HistoryInfoDto.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/exception/NotAvailableUmbrellaException.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryCustom.java
  src/main/java/upbrella/be/rent/repository/RentRepositoryImpl.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/main/java/upbrella/be/util/AesEncryptor.java
  src/main/java/upbrella/be/util/NGrinderController.java
  src/test/java/upbrella/be/config/FixtureFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceDynamicTest.java
  src/test/java/upbrella/be/util/AESTest.java
Labels: release

#310 feat: 로깅을 위한 스크립트 수정 (#309)
  deploy.sh
Labels: feat

#311 v0.3.6 dev pre-release
  deploy.sh
Labels: release

#312 [fix] api optional 필드 수정 (#299)
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
Labels: fix

#313 v0.3.7 dev pre-release
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
Labels: release

#315 [refactor] 협업지점 조회 api 성능 개선 (#272)
  src/main/java/upbrella/be/config/JacksonConfig.java
  src/main/java/upbrella/be/config/RedisCacheConfig.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: feat

#316 v0.3.8 dev pre-release
  src/main/java/upbrella/be/config/JacksonConfig.java
  src/main/java/upbrella/be/config/RedisCacheConfig.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: release
