Repository UPbrella/UPbrella_back, pull requests merged in 2023-11, with the labels that each got.

#345 [feat] 보관함 HOTP 구현
  build.gradle
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/response/LockerPasswordResponse.java
  src/main/java/upbrella/be/rent/entity/Locker.java
  src/main/java/upbrella/be/rent/exception/LockerCodeAlreadyIssuedException.java
  src/main/java/upbrella/be/rent/repository/LockerRepository.java
  src/main/java/upbrella/be/rent/service/LockerService.java
  src/main/java/upbrella/be/util/HotpGenerator.java
Labels: feat

#347 [fix] locker 테스트 오류 수정
  src/main/java/upbrella/be/rent/service/LockerService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: fix

#348 [Fix] 버그 수정 (#234)
  .github/workflows/dev-pr-test.yml
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: fix

#353 [Fix] 테스트 에러 수정
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
Labels: fix

#349 [Fix] 비밀번호 4자리 반환하도록 변경 및 해싱 방법 수정
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/response/LockerPasswordResponse.java
  src/main/java/upbrella/be/rent/exception/LockerSignatureErrorException.java
  src/main/java/upbrella/be/rent/exception/NoSignatureException.java
  src/main/java/upbrella/be/rent/service/LockerService.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: fix

#355 v0.4.6 release-dev
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/exception/MissingUmbrellaException.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
  src/test/java/upbrella/be/umbrella/integration/UmbrellaIntegrationTest.java
Labels: release

#358 [fix] 보관함 버그 수정
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/exception/UmbrellaStoreMissMatchException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: fix

#359 v0.4.7 release-dev
  src/docs/asciidoc/api/rent/rent.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/exception/UmbrellaStoreMissMatchException.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: fix

#365 [fix] store와 classification 삭제 로직 수정
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
Labels: fix

#371 [Feat] 보관함 crud api 생성 #363
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/rent/entity/Locker.java
  src/main/java/upbrella/be/rent/service/LockerService.java
  src/main/java/upbrella/be/store/controller/LockerController.java
  src/main/java/upbrella/be/store/controller/LockerExceptionHandler.java
  src/main/java/upbrella/be/store/dto/request/CreateLockerRequest.java
  src/main/java/upbrella/be/store/dto/request/UpdateLockerRequest.java
  src/main/java/upbrella/be/store/dto/response/AllLockerResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleLockerResponse.java
  src/test/java/upbrella/be/store/controller/LockerControllerTest.java
Labels: feat

#373 v1.1.0
  .github/workflows/dev-pr-test.yml
  build.gradle
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/dto/response/LockerPasswordResponse.java
  src/main/java/upbrella/be/rent/entity/Locker.java
  src/main/java/upbrella/be/rent/exception/CannotBeRentedException.java
  src/main/java/upbrella/be/rent/exception/LockerCodeAlreadyIssuedException.java
  src/main/java/upbrella/be/rent/exception/LockerSignatureErrorException.java
  src/main/java/upbrella/be/rent/exception/NoSignatureException.java
  src/main/java/upbrella/be/rent/exception/UmbrellaStoreMissMatchException.java
  src/main/java/upbrella/be/rent/repository/LockerRepository.java
  src/main/java/upbrella/be/rent/service/LockerService.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/controller/LockerController.java
  src/main/java/upbrella/be/store/controller/LockerExceptionHandler.java
  src/main/java/upbrella/be/store/dto/request/CreateLockerRequest.java
  src/main/java/upbrella/be/store/dto/request/UpdateLockerRequest.java
  src/main/java/upbrella/be/store/dto/response/AllLockerResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleLockerResponse.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/exception/MissingUmbrellaException.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
  src/main/java/upbrella/be/util/HotpGenerator.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/LockerControllerTest.java
  src/test/java/upbrella/be/umbrella/integration/UmbrellaIntegrationTest.java
Labels: release
