Repository UPbrella/UPbrella_back, pull requests merged in 2023-07, with the labels that each got.

#2 chore: gitignore 추가
  .gitignore
Labels: chore

#5 chore: 개발환경 세팅 (#1)
  .github/ISSUE_TEMPLATE/issue_template.md
  .gitignore
  HELP.md
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/upbrella/be/BeApplication.java
  src/main/resources/application.yml
  src/test/java/upbrella/be/BeApplicationTests.java
Labels: docs, chore

#6 chore: 팀 리드미 수정
  README.md
Labels: fix

#8 docs: RESTDocs User API Rest Docs 작성 및 초기 설정
  build.gradle
  src/docs/asciidoc/api/user/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/user/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/main/java/upbrella/be/util/CustomResponse.java
  src/test/java/upbrella/be/BeApplicationTests.java
  src/test/java/upbrella/be/docs/RestDocsSupport.java
  src/test/java/upbrella/be/user/UserControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: docs

#17 AWS CodeDeploy+S3 CI/CD, Gitignore Secret 추가
  .github/workflows/Dockerfile
  .github/workflows/upbrella.yml
  .gitignore
  appspec.yml
  build.gradle
  deploy.sh
  src/main/resources/application.yml
Labels: feat

#18 [Feat] store API 문서 작성 (#11)
  src/docs/asciidoc/api/login/kakao_login.adoc
  src/docs/asciidoc/api/login/naver_login.adoc
  src/docs/asciidoc/api/store/admin_find_all_store.adoc
  src/docs/asciidoc/api/store/create_store.adoc
  src/docs/asciidoc/api/store/current_location_store.adoc
  src/docs/asciidoc/api/store/current_umbrella_location.adoc
  src/docs/asciidoc/api/store/delete_store.adoc
  src/docs/asciidoc/api/store/store_find_by_id.adoc
  src/docs/asciidoc/api/store/update_store.adoc
  src/docs/asciidoc/api/store/upload_images.adoc
  src/docs/asciidoc/api/user/find_umbrella_borrowed_by_user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/login/controller/LoginController.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/CoordinateRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateStoreRequest.java
  src/main/java/upbrella/be/store/dto/request/ImagesRequest.java
  src/main/java/upbrella/be/store/dto/request/UpdateStoreRequest.java
  src/main/java/upbrella/be/store/dto/response/AllCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/AllStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/CurrentUmbrellaStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/ImageUrlsResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/main/java/upbrella/be/util/CustomResponse.java
  src/test/java/upbrella/be/login/LoginControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/user/UserControllerTest.java
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: feat

#22 [chore] soft-delete 필드 DTO에서 제거(#14)
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/umbrella/UmbrellaControllerTest.java
Labels: chore

#25 [feat] 우산 대여 API 문서 개발
  .gitignore
  daemon/8.1.1/registry.bin
  daemon/8.1.1/registry.bin.lock
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/api/user/find_umbrella_borrowed_by_user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/umbrella/UmbrellaControllerTest.java
Labels: feat

#24 [refactor] 유저와 협업지점 API 수정사항 반영 (#23)
  src/docs/asciidoc/api/login/kakao_login.adoc
  src/docs/asciidoc/api/login/naver_login.adoc
  src/docs/asciidoc/api/login/oauth.adoc
  src/docs/asciidoc/api/store/admin_find_all_store.adoc
  src/docs/asciidoc/api/store/create_store.adoc
  src/docs/asciidoc/api/store/current_location_store.adoc
  src/docs/asciidoc/api/store/current_umbrella_location.adoc
  src/docs/asciidoc/api/store/delete_store.adoc
  src/docs/asciidoc/api/store/store.adoc
  src/docs/asciidoc/api/store/store_find_by_id.adoc
  src/docs/asciidoc/api/store/update_store.adoc
  src/docs/asciidoc/api/store/upload_images.adoc
  src/docs/asciidoc/api/user/user.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/login/controller/LoginController.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/CreateStoreRequest.java
  src/test/java/upbrella/be/login/LoginControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
Labels: refactor

#29 [feat] 대여/반납 및 관리자에 의해 신고/개선 요청 내역 REST Docs 작성 (#13)
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/config/JacksonLocalDateTimeConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoriesPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/dto/response/StatusDeclarationPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/StatusDeclarationResponse.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
Labels: feat

#32 [refactor] Rest Docs 리팩토링 및 release 0.0.1(#31)
  src/docs/asciidoc/api/rent/rent.adoc
  src/docs/asciidoc/api/store/store.adoc
  src/docs/asciidoc/api/umbrella/umbrella.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/upbrella/be/config/JacksonLocalDateTimeConfig.java
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementResponse.java
  src/main/java/upbrella/be/rent/dto/response/RentalHistoryResponse.java
  src/main/java/upbrella/be/rent/dto/response/StatusDeclarationResponse.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/CurrentUmbrellaStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreImage.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaRequest.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaStatusResponse.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/login/controller/LoginControllerTest.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#42 [feat] #35 naver login
  build.gradle
  src/main/java/upbrella/be/login/controller/LoginController.java
  src/main/java/upbrella/be/login/dto/request/NaverLoginCodeRequest.java
  src/main/java/upbrella/be/login/dto/response/LoggedInUser.java
  src/main/java/upbrella/be/login/dto/response/LoggedInUserResponse.java
  src/main/java/upbrella/be/login/dto/response/NaverLoginResponse.java
  src/main/java/upbrella/be/login/dto/token/NaverOauthInfo.java
  src/main/java/upbrella/be/login/dto/token/NaverToken.java
  src/main/java/upbrella/be/login/service/OauthLoginService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/repository/UserRepository.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/resources/static/index.html
  src/test/java/upbrella/be/login/controller/LoginControllerTest.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#51 [feat] 우산 추가/수정 기능, 테스트 리팩토링(#37, #38)
  src/main/java/upbrella/be/store/StoreRepository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#52 [feat] 우산 삭제 기능 및 테스트 코드 작성(#39)
  src/main/java/upbrella/be/store/StoreRepository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#58 [feat] 우산 전체 조회, 우산 지점 조회 기능 구현 및 테스트 코드 작성(#40, #41)
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/docs/utils/RestDocsSupport.java
  src/test/java/upbrella/be/umbrella/controller/UmbrellaControllerTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#59 [feat] 사용자 우산 대여 요청 기능 구현 및 테스트 코드 작성 (#44)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/response/ConditionReportPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/ConditionReportResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementReportPageResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementReportResponse.java
  src/main/java/upbrella/be/rent/dto/response/ImprovementResponse.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/repository/ConditionReportRepository.java
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/ConditionReportService.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/entity/User.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
Labels: feat

#73 [feat] 현재 위치(지도) 기준 협업 지점 조회 기능 구현 및 테스트 코드 작성 (#70)
  src/main/java/upbrella/be/store/StoreRepository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/CoordinateRequest.java
  src/main/java/upbrella/be/store/dto/response/SingleCurrentLocationStoreResponse.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: feat

#76 [feat] 우산의 현재 위치 조회 기능 구현 및 테스트 코드 작성 (#71)
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/CurrentUmbrellaStoreResponse.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#77 [feat]/#55 store 생성 삭제
  build.gradle
  src/docs/asciidoc/api/store/store.adoc
  src/main/java/upbrella/be/config/AwsConfig.java
  src/main/java/upbrella/be/config/QueryDslConfig.java
  src/main/java/upbrella/be/login/controller/LoginController.java
  src/main/java/upbrella/be/login/dto/request/LoginCodeRequest.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/ClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateStoreRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateSubClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/UpdateStoreRequest.java
  src/main/java/upbrella/be/store/dto/response/AllClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/AllSubClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/reponse.java
  src/main/java/upbrella/be/store/entity/Classification.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreImage.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/ClassificationRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreImageRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/login/controller/LoginControllerTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: feat

#78 [feat] 로그인한 사용자 정보 조회, 로그인한 사용자가 대여 중인 우산 정보 조회 구현 및 테스트 작성 (#74, #75)
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#83 [feat] 로그인한 사용자 정보 조회, 로그인한 사용자가 대여 중인 우산 정보 조회 구현 및 테스트 작성 (#74, #75)
  src/main/java/upbrella/be/rent/repository/RentRepository.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/response/UmbrellaBorrowedByUserResponse.java
  src/main/java/upbrella/be/user/dto/response/UserInfoResponse.java
  src/test/java/upbrella/be/user/controller/UserControllerTest.java
Labels: feat

#84 [feat]: Store CRD 구현 및 테스트코드 작성(#55)
  build.gradle
  src/main/java/upbrella/be/config/AwsConfig.java
  src/main/java/upbrella/be/config/QueryDslConfig.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/request/ClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateClassificationRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateStoreRequest.java
  src/main/java/upbrella/be/store/dto/request/CreateSubClassificationRequest.java
  src/main/java/upbrella/be/store/dto/response/AllClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/AllSubClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/entity/Classification.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreImage.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/ClassificationRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreImageRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryImpl.java
  src/main/java/upbrella/be/store/service/ClassificationService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/ClassificationServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#80 [feat] JACOCO 도입 (#79)
  build.gradle
Labels: feat

#85 [feat] 가게 상세 조회 기능 구현 (#72)
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/dto/response/StoreFindByIdResponse.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepository.java
  src/main/java/upbrella/be/store/repository/StoreMetaRepositoryCustom.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/umbrella/controller/UmbrellaController.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaRequest.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaPageResponse.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaResponse.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaStatusListResponse.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaStatusResponse.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepository.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: feat

#91 [feat] CORS 초기 설정 (#80)
  src/main/java/upbrella/be/config/WebConfig.java
Labels: feat

#88 [chore] 배포 PR 테스팅 스크립트 작성 (#60)
  .github/workflows/dev-pr-test.yml
  .github/workflows/dev-release-ci.yml
  .github/workflows/production-pr-test.yml
  .github/workflows/production-release-ci.yml
Labels: chore

#93 [fix] CORS revision (#81)
  src/main/java/upbrella/be/config/WebConfig.java
Labels: fix

#94 [hot-fix] CORS revision (#81) (#93)
  src/main/java/upbrella/be/config/WebConfig.java
Labels: fix

#90 [refactor] Repository 의존성 삭제에 따른 우산, 협업지점 상세, 대여 리팩토링 및 테스트 코드 변경 (#89)
  .github/workflows/dev-pr-test.yml
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/entity/History.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/dto/request/UmbrellaRequest.java
  src/main/java/upbrella/be/umbrella/entity/Umbrella.java
  src/main/java/upbrella/be/umbrella/service/UmbrellaService.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/controller/RentControllerTest.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/umbrella/service/UmbrellaServiceTest.java
Labels: refactor
