Repository UPbrella/UPbrella_back, pull requests merged in 2023-10, with the labels that each got.

#318 [fix] 상태 신고, 개선 사항 요청 글자수 제한 (#314)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
Labels: fix

#323 feat: 로그 추가 (#322)
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/user/controller/UserController.java
Labels: feat

#321 협업지점 버그 수정
  src/docs/asciidoc/api/admin/store.adoc
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/response/AllImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/entity/BusinessHour.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/exception/NotExistBusinessHourException.java
  src/main/java/upbrella/be/store/repository/BusinessHourRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/BusinessHourService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/entity/StoreMetaTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: fix

#324 v0.4.0 dev pre-release
  src/docs/asciidoc/api/admin/store.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/dto/request/RentUmbrellaByUserRequest.java
  src/main/java/upbrella/be/rent/dto/request/ReturnUmbrellaByUserRequest.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/response/AllImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/entity/BusinessHour.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/exception/NotExistBusinessHourException.java
  src/main/java/upbrella/be/store/repository/BusinessHourRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/BusinessHourService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/entity/StoreMetaTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: release

#326 [fix] 예외처리 버그 수정 (#325)
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
Labels: fix

#332 협업지점 리팩토링
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/store/entity/StoreDetailTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: refactor, fix

#333 v0.4.1 dev pre-release
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/store/entity/StoreDetailTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
Labels: release

#335 [feat] 블랙리스트 유저는 우산을 대여할 수 없는 기능 추가 #334
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: feat

#336 [fix] 협업지점 테이블 조인 시 버그 발생으로 인해 우산만 반환 (#331)
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaWithHistory.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
Labels: fix

#338 [feat] 계좌정보 등록 / 수정 시 숫자만 입력할 수 있도록 변경 #337
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/request/UpdateBankAccountRequest.java
  src/main/java/upbrella/be/user/validation/OnlyNumbers.java
  src/main/java/upbrella/be/user/validation/OnlyNumbersValidator.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
Labels: feat

#339 v 1.0.0 release
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaWithHistory.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/request/UpdateBankAccountRequest.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/user/validation/OnlyNumbers.java
  src/main/java/upbrella/be/user/validation/OnlyNumbersValidator.java
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#340 v1.0.0 release
  src/docs/asciidoc/api/admin/store.adoc
  src/main/java/upbrella/be/rent/controller/RentController.java
  src/main/java/upbrella/be/rent/controller/RentExceptionHandler.java
  src/main/java/upbrella/be/rent/service/RentService.java
  src/main/java/upbrella/be/store/controller/StoreController.java
  src/main/java/upbrella/be/store/controller/StoreExceptionHandler.java
  src/main/java/upbrella/be/store/dto/response/AllImageUrlResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleBusinessHourResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleClassificationResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleStoreResponse.java
  src/main/java/upbrella/be/store/dto/response/SingleSubClassificationResponse.java
  src/main/java/upbrella/be/store/entity/BusinessHour.java
  src/main/java/upbrella/be/store/entity/StoreDetail.java
  src/main/java/upbrella/be/store/entity/StoreMeta.java
  src/main/java/upbrella/be/store/exception/NotExistBusinessHourException.java
  src/main/java/upbrella/be/store/repository/BusinessHourRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepository.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryCustom.java
  src/main/java/upbrella/be/store/repository/StoreDetailRepositoryImpl.java
  src/main/java/upbrella/be/store/service/BusinessHourService.java
  src/main/java/upbrella/be/store/service/StoreDetailService.java
  src/main/java/upbrella/be/store/service/StoreImageService.java
  src/main/java/upbrella/be/store/service/StoreMetaService.java
  src/main/java/upbrella/be/umbrella/dto/response/UmbrellaWithHistory.java
  src/main/java/upbrella/be/umbrella/repository/UmbrellaRepositoryImpl.java
  src/main/java/upbrella/be/user/controller/UserController.java
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
  src/main/java/upbrella/be/user/dto/request/UpdateBankAccountRequest.java
  src/main/java/upbrella/be/user/service/UserService.java
  src/main/java/upbrella/be/user/validation/OnlyNumbers.java
  src/main/java/upbrella/be/user/validation/OnlyNumbersValidator.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/upbrella/be/config/FixtureBuilderFactory.java
  src/test/java/upbrella/be/rent/service/RentServiceTest.java
  src/test/java/upbrella/be/store/controller/StoreControllerTest.java
  src/test/java/upbrella/be/store/entity/StoreDetailTest.java
  src/test/java/upbrella/be/store/entity/StoreMetaTest.java
  src/test/java/upbrella/be/store/service/BusinessHourServiceTest.java
  src/test/java/upbrella/be/store/service/StoreDetailServiceTest.java
  src/test/java/upbrella/be/store/service/StoreImageServiceTest.java
  src/test/java/upbrella/be/store/service/StoreMetaServiceTest.java
  src/test/java/upbrella/be/user/service/UserServiceTest.java
Labels: release

#342 fix: 버그 수정 (#341)
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
Labels: fix

#343 fix: 버그 수정 (#341) (#342)
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
Labels: release

#344 fix: 버그 수정 (#341) (#342)
  src/main/java/upbrella/be/user/dto/request/JoinRequest.java
Labels: release
